baseURL = 'https://static.makehumancommunity.org/'
languageCode = 'en-us'
title = 'MakeHuman Community'
theme = 'relearn'
uglyurls = true

publishDir = "build"

[params]
#disableBreadcrumb = true
disableLandingPageButton = true
disableNextPrev = true
disableSearch = true
showVisitedLinks = false
themeVariant = "makehuman"
collapsibleMenu = true
primaryFilesUrl = "https://files2.makehumancommunity.org"
secondaryFilesUrl = "http://files.makehumancommunity.org"

[menu]
    [[menu.shortcuts]]
        name = "Original site"
        url = "http://www.makehumancommunity.org"
        weight = 1

    [[menu.shortcuts]]
        name = "Forum"
        url = "http://www.makehumancommunity.org/forum/"
        weight = 2

    [[menu.shortcuts]]
        name = "GitHub"
        url = "https://github.com/makehumancommunity"
        weight = 3

    [[menu.shortcuts]]
        name = "Facebook"
        url = "https://www.facebook.com/makehuman"
        weight = 4

    [[menu.shortcuts]]
        name = "YouTube"
        url = "https://www.youtube.com/channel/UC8f7BA98RQHl70sEta5KXxQ"
        weight = 5

    [[menu.shortcuts]]
        name = "Patreon"
        url = "https://www.patreon.com/makehuman"
        weight = 6


